url.Url: add __hash__ method
I've been seeing a lot of messages like this:

"""
Traceback (most recent call last):
  File "<redacted>", line 492, in upload_video
    self.entry = self.youtube.service.InsertVideoEntry(new_entry, str(file_to_upload))
  File "<redacted>/lib/python3.4/site-packages/gdata/youtube/service.py", line 663, in InsertVideoEntry
    converter=gdata.youtube.YouTubeVideoEntryFromString)
  File "<redacted>/lib/python3.4/site-packages/gdata/service.py", line 1239, in Post
    media_source=media_source, converter=converter)
  File "<redacted>/lib/python3.4/site-packages/gdata/service.py", line 1306, in PostOrPut
    multipart[2]], headers=extra_headers, url_params=url_params)
  File "<redacted>/lib/python3.4/site-packages/atom/__init__.py", line 94, in optional_warn_function
    return f(*args, **kwargs)
  File "<redacted>/lib/python3.4/site-packages/atom/service.py", line 186, in request
    auth_token = self.token_store.find_token(url)
  File "<redacted>/lib/python3.4/site-packages/atom/token_store.py", line 85, in find_token
    if url in self._tokens:
TypeError: unhashable type: 'Url'
"""

The return value of Url.get_param_string is subject to the hash randomization
that is enabled by default in Python >= 3.3, but this is not an issue since
we only care that the values are consistent within one execution of the Python
interpreter.